---
- name: set initrd modules
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^MODULES='
    line: 'MODULES="pwm-lpss pwm-lpss-platform"'
  notify:
  - update boot
  tags:
  - boot

- name: set HOOKS for chrooted system (iso creation = yes)
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: 'HOOKS="base udev memdisk archiso_shutdown archiso archiso_loop_mnt archiso_pxe_common archiso_pxe_nbd archiso_pxe_http archiso_pxe_nfs archiso_kms block modconf filesystems keyboard"'
    create: yes
  when: ansible_facts.chroot == 'true'
  notify:
  - update boot
  tags:
  - boot

- name: set HOOKS for running system (iso creation = no)
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^HOOKS='
    line: 'HOOKS="base systemd block btrfs autodetect modconf filesystems fsck"'
    create: yes
  when: ansible_facts.chroot == 'false'
  notify:
  - update boot
  tags:
  - boot