---
- name: check if running in chroot (iso creation)
  shell: |
    if [ "$(stat -c %d:%i /)" != "$(stat -c %d:%i /proc/1/root/.)" ]; then
      echo "chroot"
    fi
  register: chroot
  changed_when: False
  tags:
  - boot

- name: install ubuntu casper packages (iso creation = yes)
  apt: name="{{ item }}"
  with_items:
  - casper
  - lupin-casper
  when: chroot.stdout.find('chroot') != -1 and ansible_distribution == 'Ubuntu'
  tags:
  - boot

- name: create loop module config (iso creation = yes)
  lineinfile:
    path: /etc/modprobe.d/loop.conf
    line: "options loop max_loop=8"
    create: yes
  when: chroot.stdout.find('chroot') != -1
  tags:
  - boot

- name: add modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
    create: yes
  with_items:
  - loop
  - overlay
  - pwm-lpss
  - pwm-lpss-platform
  - squashfs
  notify:
  - update boot
  tags:
  - boot