---
- name: install essential packages (this may take a while)
  package: name="{{ item }}"
  with_items:
  - dconf-cli
  - dconf-editor
  - i965-va-driver
  - mesa-utils
  - va-driver-all
  - vainfo
  - x11-xserver-utils
  tags:
  - xorg